version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-video-clip"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wh3uk63epz22"
s3_prefix = "serverless-video-clip"
parameter_overrides = "MediaLiveChannelIdIndexName=\"medialive_channel_id-index\" ClipsTableEventIdIndex=\"event_id-index\" VotesTableEventIdIndex=\"clip_id-index\""
